#!/bin/sh 
# 
# VIM Tag file Generator
#
# Alvaro Navarro <anavarro@achtung.es>

vimdir=${HOME}/.vim
tagdir=${vimdir}/tags

cflags=`which ctags`

if [ -z ${cflags} ]; then
    echo "Error: Exuberant ctags must be installed before continue"
    exit 1
fi

if [ ! -d ${tagdir} ]; then
    mkdir ${tagdir}
fi

for i in $@;
do
    if [ ! -d $i ]; then
        echo "No sources found in $i. Skipping..."
    else
        tagfile=${tagdir}/`basename $i`
        vimfile=${tagdir}/`basename $i.vim`

        echo "Creating $tagfile"
        ctags -R --sort=1 --c++-kinds=+p --fields=+iaS --extra=+q+f --language-force=C++ -f ${tagfile} $i

        echo "Adding $i to $vimfile..."
        echo "set path+=$i/**"      >  ${vimfile}
        echo "set tags+=${tagfile}" >> ${vimfile}
    fi
done

