#!/bin/sh
#
# VIM Tag file Generator
#
# Alvaro Navarro <anavarro@achtung.es>

vimdir=${HOME}/.vim
tagdir=${vimdir}/tags

cflags=`which ctags`

usage() {
	echo "Usage: $0 <tag_id> <header_directory>"
	exit 1
}

if [ -z ${cflags} ]; then
    echo "Error: Exuberant ctags must be installed before continue"
    exit 1
fi

if [ $# -ne 2 ]; then
	usage
fi

if [ ! -d ${tagdir} ]; then
    mkdir -p ${tagdir}
fi

if [ ! -d $2 ]; then
	echo "Error: No sources found in $2."
	usage
fi

tagfile=${tagdir}/`basename $1`
vimfile=${tagdir}/`basename $1.vim`

echo "Creating $tagfile"
ctags -R --sort=1 --c++-kinds=+pl --fields=+iaS --extra=+q+f --language-force=C++ -f ${tagfile} $2

echo "Adding $1 to $vimfile..."
echo "set path+=$2/**"      >  ${vimfile}
echo "set tags+=${tagfile}" >> ${vimfile}

